name: Wasmd Demo Docker
on: push


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
         registry: docker.pkg.github.com
         password: ${{ secrets.GITHUB_TOKEN }}
         image: crg

   
   
   
   

